# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
